[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
phf_codegen = "0.11.2"
string_cache_codegen = "0.5.2"
xflags = "0.3.2"
